### ISSUE TITLE
Add API for registering a custom format generator

### ISSUE THREAD

**Issue by whitlockjc** [apigee-127/sway#100]
Since the OpenAPI Specification allows you to use any `format` you want, we should add a top-level API for registering custom format generators like we do for [custom validators](https://github.com/apigee-127/sway/blob/master/docs/API.md#module_Sway..SwaggerApi+registerValidator).

Originally requested in #98.

**Comment by amarzavery** [comment]
What is the ETA for this?

**Comment by whitlockjc** [comment]
Like most of `json-refs` and `sway`, I work on it in my free time and I've not had much of that lately.  I am desperately trying to get them released ASAP but no guarantees on an ETA.  Contributions welcome.
