### ISSUE TITLE
Does it support jsdoc and json files?

### ISSUE THREAD

**Issue by mrchief** [apigee-127/sway#105]
I'm currently using swagger-parser and it supports yaml, jsdoc, and json formats. Does sway support them as well or is it just yaml? 

I [stumbled upon](https://github.com/apigee-127/swagger-tools/issues/227#issuecomment-129699454) sway while researching answers to https://github.com/BigstickCarpet/swagger-parser/issues/50.

**Comment by whitlockjc** [comment]
sway supports json and yaml.  I assume by jsdoc support you mean parsing JavaScript source code and wiring things together based on the jsdoc tags?  Regardless, it's not supported.
