### ISSUE TITLE
Adding the standalone min js throws Range out of order in character class error

### ISSUE THREAD

**Issue by bjdash** [apigee-127/sway#107]
I added the standalone min file to my html and its throwing below error in console. However adding teh unminified version worsk fine.

sway-standalone-min.js:26 Uncaught SyntaxError: Invalid regular expression: /[Ã€-ÃŸ][Â€-Â¿]|[Ã -Ã¯][Â€-Â¿]{2}|[Ã°-Ã·][Â€-Â¿]{3}/: Range out of order in character class

**Comment by whitlockjc** [comment]
Can you confirm if this is still the case, on `master`?

**Comment by whitlockjc** [comment]
Closing until more information becomes available.
