### ISSUE TITLE
Empty references cause an endless loop

### ISSUE THREAD

**Issue by webron** [apigee-127/sway#111]
It looks like an empty reference value can throw sway into an endless loop, when running in a browser ending with a crash. For example:

```yaml
  $ref: '' 
```

**Comment by whitlockjc** [comment]
Based on the _JSON Pointer_ spec, this is the same as a reference to the root of the document.  So it seems we need to make sure that we handle this.

**Comment by noahdietz** [comment]
I confirmed that what is in master is unable to reproduce this issue. 

@whitlockjc I believe your upgrade to `json-refs` 3.0.0 was the fix. I think we can close if you are ready to.
