### ISSUE TITLE
Only allow one body parameter

### ISSUE THREAD

**Issue by whitlockjc** [apigee-127/sway#116]
Per the Swagger 2.0 specification, an operation can have only one `body` parameter and we need to enforce this.

Originally reported here: https://github.com/apigee-127/swagger-tools/issues/461

**Comment by noahdietz** [comment]
I think this can be closed:
* check in validators [here](https://github.com/apigee-127/sway/blob/master/lib/validation/validators.js#L625-L630)
* test for it [here](https://github.com/apigee-127/sway/blob/master/test/test-api.js#L1198)

I verified on API studio that the proper error is thrown when two `body` params are defined.

**Comment by whitlockjc** [comment]
Good catch.
