### ISSUE TITLE
validateRequest does not throw an error when stringified (JSON.stringify) version of the request body is provided

### ISSUE THREAD

**Issue by amarzavery** [apigee-127/sway#119]
I was testing validateRequest() to see if it correctly throws an error in the following scenarios
- if a property of the body parameter is set to null and the swagger spec says that it should be of type string. 
- if a property of the body parameter is of type integer and the user provides a string instead

Initially validateRequest output was `{ errors: [], warnings: [] }`. I was amazed to see this. I was not expecting this.
Then I found that while constructing the request object, I was doing 
`this.body = JSON.stringify(options.body)` , where options is the parameter to my request wrapper.

As soon as I removed that and passed the body as-is validateRequest worked as expected.

Hence, I think this is a bug.

- Either validateRequest should somehow find out that the provided body is a stringified version and do  `JSON.parse()` and validate correctly.
- OR it should do type validation. In most cases where the request body is usually an object, `typeof` check should fail and vlidateRequest should throw correct error. (This will absorb the error when body is of type string but it will do the correct thing for other scenarios, which will be better than what is happening today).

**Comment by whitlockjc** [comment]
Can you provide the pertinent portion of your Swagger document _(the parameter definition and any referenced definitions)_ and an example that reproduces the issue?

**Comment by whitlockjc** [comment]
I'm closing this until you provide more information.
