### ISSUE TITLE
global (api level) security ignored when resolving operation.securityDefinitions

### ISSUE THREAD

**Issue by Sayene** [apigee-127/sway#120]
After upgrade from sway 0.6 to 1.0 (with swagger-node-runner):
* global (api level) security definition is not resolved into req.swagger.operation.securityDefinitions object - which is now an empty object {} 
* operation.securityDefinitions is resolved with right definitions only when security definition is added to operation level
Global security definition should be resolved into operation.securityDefinitions unless overridden by operation level security.

**Comment by whitlockjc** [comment]
I think this is a bug that is better filed with `swagger-node-runner`.  Basically, when `swagger-node-runner` did its work to update to sway 1.0, it didn't update for the security changes.  These were [documented in the release notes](https://github.com/apigee-127/sway/blob/master/RELEASE_NOTES.md#v100-2016-04-04).

**Comment by motorro** [comment]
@whitlockjc, there is still a problem in sway code. Please see #145

**Comment by whitlockjc** [comment]
Will do, thanks.

**Comment by motorro** [comment]
@whitlockjc have you got a chance to check the PR? Thanks!
