### ISSUE TITLE
sway ignores required option on parameters

### ISSUE THREAD

**Issue by Celadora** [apigee-127/sway#129]
In my Swagger definition we have:

      parameters:
        - name: photo
          in: formData
          description: The uploaded portrait photo
          required: false
          type: file

This will throw an error.
Error: req.files must be provided for 'formData' parameters of type 'file'

The problem is that Sway isn't checking if required is false, and so these lines will always throw an error when req.files hasn't been set by something like Multer.

One solution would be to put Multer first, before Swagger, but that defeats the purpose of having validation before processing. And since Sway can't get field names for mulitpart data before *something* consumes the stream, we need a way to simply turn off requiring the validation in the first place, while leaving in place the documentation that Swagger offers.

in parameters.js at line 142
```
      if (type === 'file') {
      if (_.isUndefined(req.files)) {
        if(throw new Error('req.files must be provided for \'formData\' parameters of type \'file\'');
      }

      value = req.files[this.name];
    } else {
      if (_.isUndefined(req.body)) {
        throw new Error('req.body must be provided for \'formData\' parameters');
      }
      value = req.body[this.name];
    }
```

should become:

```
      if (type === 'file') {
      if (_.isUndefined(req.files)) {
        if(this.required) throw new Error('req.files must be provided for \'formData\' parameters of type \'file\'');
        else break;
      }

      value = req.files[this.name];
    } else {
      if (_.isUndefined(req.body)) {
        if(this.required) throw new Error('req.body must be provided for \'formData\' parameters');
        else break;
      }
      value = req.body[this.name];
    }
```

So that sway will ignore parameters of type "file" that are not required.

Is this something that is acceptable to patch with a pull request?

Thank you!

**Comment by whitlockjc** [comment]
This is a simple fix I can whip up.  To fix this, we should treat `req.files` as missing as fine when `required` is `false`.  We could possibly do the same with the other parsers as well.
