### ISSUE TITLE
Remove support for items being an array

### ISSUE THREAD

**Issue by whitlockjc** [apigee-127/sway#130]
While JSON Schema allows for the `items` property of an array to be either an `object` or an `array` of `object`s, OAI does not.

**Comment by noahdietz** [comment]
Just for clarification, this is saying "2D arrays" are not allowed in OAI? i.e. it is invalid to have a response schema, for example, that is `type: array` with `items` of `type: array`? Thanks. Just trying to clarify.

I did read this in the 3.0 spec [here](https://github.com/OAI/OpenAPI-Specification/blob/master/versions/3.0.0.md#properties) but clarity can't hurt 🐼

**Comment by whitlockjc** [comment]
Actually, this isn't required.  We might have some code in there that allows it but the structural validation would keep it from happening.
