### ISSUE TITLE
Request validation should support DELETE and PATCH

### ISSUE THREAD

**Issue by whitlockjc** [apigee-127/sway#134]
https://github.com/apigee-127/swagger-tools/issues/480

**Comment by noahdietz** [comment]
_copied my comments from https://github.com/apigee-127/swagger-tools/issues/480_

@whitlockjc should the method check be removed entirely (every method's body, if present, will be validated against the desired content type) or should we exclude `GET`? Personally, I think we should exclude the `GET`, but I'm not married to that.

Furthermore, `HEAD` should follow `GET` in its treatment, and `OPTIONS` isn't explicitly excluded, but according to RFC, it isn't technically supposed to have a request body, however in the event that `OPTIONS` does include a request body, it *must* include a `Content-Type` header. [source](https://tools.ietf.org/html/rfc7231#section-4.3.7)

**Comment by whitlockjc** [comment]
Maybe we just remove the filtering based on HTTP method.  If _"any HTTP request message is allowed to contain a message body"_, who are we to disallow sending and validating it?

**Comment by noahdietz** [comment]
Cool by me. I can change my PR to remove that conditional. Do you still want tests for various HTTP methods to make sure they are being validated as well, or just the one already existing exhaustive test is fine?
