### ISSUE TITLE
ptr must be a JSON Pointer

### ISSUE THREAD

**Issue by amestsantim** [apigee-127/sway#135]
This is my swagger.json file which has the proper reference but somehow I'm getting the "ptr must be a JSON Pointer" error in the online editor.

{
    "swagger": "2.0",
    "info": {
        "title": "SMS Api",
        "description": "This is a SMS Api that works on top of Kannel.",
        "contact": {
            "name": "My Name",
            "email": "example@example.com"
        },
        "version": "1.0.0"
    },
    "host": "sms_api.me",
    "basePath": "/api/v1",
    "schemes": [
        "http"
    ],
    "consumes": [
        "application/vnd.api+json"
    ],
    "produces": [
        "application/vnd.api+json"
    ],
    "paths": {
        "/applications": {
            "post": {
                "summary": "Creates an application",
                "description": "Acceptes a JSON object containing the required attributes and creates an application.",
                "parameters": [
                    {
                        "name": "name",
                        "in": "body",
                        "description": "Name of the application",
                        "required": true,
                        "schema": {
                            "$ref": "#definitions/ValidationError"
                        }
                    },
                    {
                        "name": "keyword",
                        "in": "body",
                        "description": "Keyword of the application",
                        "required": true,
                        "schema": {
                            "$ref": "#definitions/ValidationError"
                        }
                    },
                    {
                        "name": "receive_url",
                        "in": "body",
                        "description": "The url where the application will receive MO messages",
                        "required": true,
                        "schema": {
                            "$ref": "#definitions/ValidationError"
                        }
                    },
                    {
                        "name": "callback_url",
                        "in": "body",
                        "description": "The url where the application will receive delivery reports (dlr) for MT messages it sent",
                        "required": false,
                        "schema": {
                            "$ref": "#definitions/ValidationError"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "A JSON object containing the created application",
                        "schema": {
                            "$ref": "#definitions/ValidationError"
                        }
                    },
                    "422": {
                        "description": "Validation error",
                        "schema": {
                            "$ref": "#definitions/ValidationError"
                        }
                    },
                    "default": {
                        "description": "All other errors",
                        "schema": {
                            "$ref": "#definitions/ValidationError"
                        }
                    }
                }
            }
        },
        "/applications/{appId}": {
            "get": {
                "summary": "Returns details of an application with id of appId",
                "description": "Returns an application",
                "parameters": [
                    {
                        "name": "appId",
                        "in": "path",
                        "description": "Id of the application",
                        "required": true,
                        "type": "integer"
                    }
                ],
                "responses": {
                    "422": {
                        "description": "Validation error",
                        "schema": {
                            "$ref": "#definitions/ValidationError"
                        }
                    },
                    "default": {
                        "description": "All other errors",
                        "schema": {
                            "$ref": "#definitions/ValidationError"
                        }
                    }
                }
            }
        },
        "/applications/{appId}/mt_messages": {
            "post": {
                "summary": "Send mobile terminated (mt) SMS message for an application with appId",
                "responses": {
                    "201": {
                        "description": "A JSON object containing the sent message and it's database id"
                    },
                    "422": {
                        "description": "A JSON object containing validation errors"
                    }
                }
            }
        },
        "/applications/{appKeyword}/mo_messages": {
            "get": {
                "summary": "Receive delivery report for mt message sent by application with keyword appKeyword",
                "responses": {
                    "201": {
                        "description": "A JSON object containing the sent message and it's database id"
                    }
                }
            }
        }
    },
    "definitions": {
        "ValidationError": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "integer",
                    "description": "This is the error code"
                },
                "message": {
                    "type": "string"
                }
            }
        }
    },
    "securityDefinitions": {
        "api_key": {
            "type": "apiKey",
            "name": "api_key",
            "in": "header",
            "scopes": {
                "write:pets": "modify pets in your account",
                "read:pets": "read your pets"
            }
        }
    }
}

**Comment by whitlockjc** [comment]
The reason you're getting these errors is because your `$ref` values are not valid.  For example, in one place you use `#definitions/ValidationError` but that should really be `#/definitions/ValidationError`.  If you look at the [JSON Pointer spec](https://tools.ietf.org/html/rfc6901#section-6), you'll see the only fragment-based JSON Pointer without a `/` after the `#` is `#` itself, which is a reference to the root of the document.  If you fix your references to be valid, this error will go away.

**Comment by amestsantim** [comment]
Yes, you are indeed right, I guess I was just blinded from staring too much at the json and not seeing the missing /.
Thanks!
