### ISSUE TITLE
CLI for validation

### ISSUE THREAD

**Issue by IvanGoncharov** [apigee-127/sway#14]
I want to switch from `swagger-tools` to `sway`.
What's blocking me is absence of CLI tool which I can you inside build scripts.
Is it planned feature?

**Comment by whitlockjc** [comment]
I don't think sway will have a CLI but we will be porting `swagger-node` to use sway soon.  Then you can run `swagger validate PATH_OR_URL` like you can with swagger-tools right now.  Will that work for you?

**Comment by mohsen1** [comment]
https://github.com/swagger-api/swagger-node/issues/259
https://github.com/swagger-api/swagger-node/issues/258

**Comment by IvanGoncharov** [comment]
> Will that work for you?

@whitlockjc Yes, definitely.
Do you have rough estimate when `swagger-node` will migrate on `sway`?

**Comment by mohsen1** [comment]
@IvanGoncharov Please follow https://github.com/swagger-api/swagger-node/issues/275. I believe sway is on par with swagger-tools for those commands we only need to use it in swagger-node. Is that true @whitlockjc? 

@IvanGoncharov You're welcome to work on that.

**Comment by whitlockjc** [comment]
That's correct.  Validation in sway is better than in swagger-tools so hooking up `swagger validate` to use it should be great.

**Comment by whitlockjc** [comment]
Closing this in favor of the work in swagger-node.
