### ISSUE TITLE
Swagger global security definition not working!

### ISSUE THREAD

**Issue by randomcatgamer** [apigee-127/sway#146]
Using the global security definition does not work.
```
...
securityDefinitions:
   APIKeyHeader:
     type: apiKey
     in: header
     name: X-jwttoken
security:
        - APIKeyHeader: []
...
/someendpoint:
    x-swagger-router-controller: someendpoint
    get:
      description: a description
      operationId: someendpointMethod
      produces:
        - application/json
      parameters:
        - name: X-jwttoken
          in: header
          description: jwt wso2 token
          required: false
          type: string
      responses:
        '200':
          description: Success
```
The error I get is:
__Cannot read property 'type' of undefined","stacktrace":"TypeError: Cannot read property 'type' of undefined    
   at getScopeOrAPIKey (D:\\devcat\\dev_workspace\\workspace\\backend-marketplace-productactivation\\node_modules\\swagger-node-runner\\fittings\\swagger_security.js:80:25)
    at andCheck (D:\\devcat\\dev_workspace\\workspace\\backend-marketplace-productactivation\\node_modules\\swagger-node-runner\\fittings\\swagger_security.js:51:43)_

If I put the security definition within each of my paths (instead of global) it works.

Also, with swagger-node-mw 0.1.0 the global definition works.

**Comment by whitlockjc** [comment]
This will be resolved via #145.

**Comment by noahdietz** [comment]
#145 was merged, and will come in the next release.

@randomcatgamer can you pull master, link to the local copy and verify that the fix works? If you can't do this, please verify as soon as there is a release so that we can close the issue.

**Comment by whitlockjc** [comment]
This is a duplicate of #120.
