### ISSUE TITLE
Ensure path matching is case-sensitive

### ISSUE THREAD

**Issue by whitlockjc** [apigee-127/sway#147]
Per [RFC3986 6.2.2.1](https://tools.ietf.org/html/rfc3986#section-6.2.2.1), it seems that all URI components other than scheme and host are suppose to be case-_sensitive_.  This is a bug and should be fixed.

Originally reported in `swagger-tools`: https://github.com/apigee-127/swagger-tools/issues/519

**Comment by noahdietz** [comment]
Verified that this bug exists.

I added the following test to [`test-path.js:65`](https://github.com/apigee-127/sway/blob/master/test/test-path.js#L65):
```js
// for reference: '/v2/pet/{petId}'
assert.ok(!_.isArray(pathObject.regexp.exec(swaggerApi.definitionFullyResolved.basePath + '/Pet/1'))); // /v2/Pet/1
```

The suggested fix was to add the `sensitive: true` flag to the use of `path-to-regexp`. In sway, this is used in a path's regexp compilation [here](https://github.com/apigee-127/sway/blob/master/lib/types/path.js#L80).  Adding it here fixed the issue, making the test pass.
