### ISSUE TITLE
Feature Request: support sway.getOperation(operationId)

### ISSUE THREAD

**Issue by osher** [apigee-127/sway#152]
If that sounds reasonable - I can work on a PR for you :)

**Comment by whitlockjc** [comment]
Maybe `#getOperationById(operationId)`?  `#getOperation(methodOrId)` could end up with ambiguous results.  _(I do think you'd have to go out of your way for this but I'd rather not rely on the end user)_

**Comment by osher** [comment]
I did give a thought about it 

First - not to confuse with [`PathObject.getOperation`](https://github.com/apigee-127/sway/blob/master/docs/API.md#module_Sway..Path+getOperation).

we're discussing [`SwayAPI.getOperation`](https://github.com/apigee-127/sway/blob/master/docs/API.md#module_Sway..SwaggerApi+getOperation)

Basically it implements already two overloadings, now distinct probably by arity:
`SwayAPI.getOperation(1)` - which is understood as
 `    SwayAPI.getOperation(request:object)`
and `SwayAPI.getOperation(2)` - which is understood as
`     SwayAPI.getOperation(path:string, method:pesudo-enum-string)`

So I'm basically offering the distinction between 
`SwayAPI.getOperation(1:IncomingMessage)` - which is `SwayAPI.getOperation(request:IncomingMessage)`
to
`SwayAPI.getOperation(1:string)` - which is `SwayAPI.getOperation(operationId:string)`

It does change the docs to
### SwaggerApi.getOperation(reqOrOperationIdOrPath, [method]) => Operation
I think that worths it

Anyway - you're the designer of this tool, and I'll comply with your decision.

LMK what will it be 👍

**Comment by whitlockjc** [comment]
My initial concern was that you could have one operation with a method of _X_ and another operation with an `operationId` of _X_ but in all honesty, that's a stretch.  So I think having `#getOperation(methodOrOperationIdOrRequest)` is reasonable.  We don't need a separate method for this.
