### ISSUE TITLE
getPath returns undefined when used whith router (express.Router()), baseUrl ignored

### ISSUE THREAD

**Issue by chelfi** [apigee-127/sway#156]
When using a router (express.Router()) instead on the app itself (express()), SwaggerExpress is unable to route the request to the right controller. error is happening in the sway lib when resolving the path. Here is how to reproduce it.
- prepare a swagger-app1.yaml file with basePath: /v1/app1 and a path /hello implemented in for example in controller helloController and operationId sayHello

- in app.js:
'use strict';
const SwaggerExpress = require('swagger-express-mw');
const                express = require('express');

const app = express();

const app1Config = { appRoot: __dirname, swagger:'api/swagger/swagger-app1.yaml' };
const app1Router = express.Router();

SwaggerExpress.create(app1Config, (err, app1SwaggerExpress) => {
        if (err) { throw err; }
        app1SwaggerExpress.register(app1Router);
        //app1Router mounted on basePath
        app.use(app1SwaggerExpress.runner.api.basePath, app1Router);   
        app.listen(8080);
});

- when I perform: curl http://localhost:8080/v1/app1/hello I receive a 404 not found response
expected to hit the sayHello method and receive the return text.

I debugged the swap/lib/types/api.js and I noticed that the getPath method uses pathOrReq.url which is in this case /hello and ignores pathOrReq.baseUrl which is /v1/app1. when using /hello to match the regex /v1/app1/hello... it does not find any and returns undefined. if instead it uses pathOrReq.originalUrl that would be solved.

to work around it I added:
app1Router.use( (req, res, next) => { req.url = req.originalUrl;  next()});

but this rewrites the req.path as well.

**Comment by whitlockjc** [comment]
I'll get this looked into and fixed in short order.

**Comment by whitlockjc** [comment]
The interface for `sway` is that `req.url` is used _but_ I think we we also check for `req.originalUrl`, and use that first if it's there, this would fix the situation.  Is that correct?

**Comment by chelfi** [comment]
Thank you Jeremy. that's perfect.
