### ISSUE TITLE
Update the NPM build

### ISSUE THREAD

**Issue by fed135** [apigee-127/sway#157]
The NPM version dates to last year, locked with dependencies from that time.

```
├─┬ sway@1.0.0
│   ├─┬ json-schema-faker@0.2.16
│   │   ├── faker@3.1.0
```
Faker 3.1 didn't have a `.npmignore` file at that time. That dependency alone is >68Mb
I was wondering why our node_modules folder was so big...

**Comment by whitlockjc** [comment]
[package.json#L69](https://github.com/apigee-127/sway/blob/master/package.json#L69) shows `^0.5.0-rc8` which includes `faker@4.1.0`.  This should had been fixed on `master` in 85ebf329c623e42c37725c80e780e7a212e206f6

**Comment by fed135** [comment]
@whitlockjc  It may be on master here, but it hasn't been published on NPM: https://www.npmjs.com/package/sway

The project has been on version 1.0.0 since  Apr 4, 2016!

**Comment by whitlockjc** [comment]
I understand.  As for the last release being a while back, sorry for the delay.  We're working on a new release but we haven't finished it yet.  Feel free to get involved and help out.

**Comment by fed135** [comment]
@whitlockjc Do you have a list of bugs or features that need to be worked on in particular? What's preventing you from releasing now?

**Comment by whitlockjc** [comment]
We could release right now.  If you look at the [release notes](https://github.com/apigee-127/sway/blob/master/RELEASE_NOTES.md#tbd), you'll see that there are a number of changes on `master` that could be useful.  I'd like to push a `1.1.0` release with those changes and possibly cherry-pick some changes for a `1.0.1`.  As for what's left, `1.1.0` should get all issues fixed that are not breaking changes.  I need to look.

**Comment by MikeRalphson** [comment]
Would seriously love a `1.0.1` or `1.1.0` release, just to get the benefit of the newer `json-refs` release. Don't care about new features (assuming it passes the same tests as the existing release).

**Comment by whitlockjc** [comment]
I apologize, let me see if we can get something done sooner.

**Comment by MikeRalphson** [comment]
No need to apologise, that was just meant as a positive testing report. :)
