### ISSUE TITLE
Unknown primitive "file" in /type

### ISSUE THREAD

**Issue by gruberchris** [apigee-127/sway#159]
I just started to use Sway for my project. I am impressed with it so far. I did find one issue regarding when a parameter is declared as type "file". My understanding is that under OpenAPI v2, "file" was a legal type but under OpenAPI v3, it is not. I get an error saying "unknown primitive "file" in /type" because the "/pet/{petId}/uploadImage" route in this public swagger example http://petstore.swagger.io/v2/swagger.json has such a parameter declared.

Which version of OpenAPI is sway v1.0.0 on? If it is on OpenAPI v2, why doesn't it support the "file" type and is there a workaround?

When the day comes that Sway also supports OpenAPI v3, will there be an option to specify a particular version of OpenAPI you want to use?

**Comment by whitlockjc** [comment]
`sway` uses OpenAPI v2.0 and `type: file` should be valid.  Do you have a reproduction recipe?

**Comment by whitlockjc** [comment]
Without a reproduction recipe, I cannot help.  We have numerous tests for `type: file` so I'm not sure how we could be doing it wrong without some help.

**Comment by gruberchris** [comment]
I think you closed this a little too fast.

Here is my code that results in the error i described when processing the sample endpoint I described.

`import Sway from 'sway';

let cachedSwayApi;

export default class SwayApi {
  static createSwayApi(swaggerSpec) {
    return new Promise((resolve, reject) => {
      Sway.create({definition: swaggerSpec}).then(swayApi => {
        cachedSwayApi = swayApi;
        resolve();
      }).catch(error => {
        cachedSwayApi = undefined;
        reject(`Error while creating Sway api from endpoint's swagger definition: ${error}`);
      });
    });
  }

  static getSampleRequestsByPathAndMethod(path, method) {
    if(!cachedSwayApi) return {};
    const operation = cachedSwayApi.getOperation(path, method);
    return operation.getParameters().map(param => param.getSample());
  }
}`

**Comment by whitlockjc** [comment]
I don't mind reopening it, but without a reproduction recipe there was nothing to go on.

**Comment by whitlockjc** [comment]
Do you have an example OAS that reproduces this?  That's more important than your JS code.

**Comment by gruberchris** [comment]
@whitlockjc Not sure what you are asking for. Is the "example OAS" you are asking for the swagger.json I am using? If so, I'm using this public swagger.json example, http://petstore.swagger.io/v2/swagger.json

**Comment by gruberchris** [comment]
![image](https://user-images.githubusercontent.com/2971844/33614961-68e93f1c-d99e-11e7-93c6-6653d57bc170.png)

**Comment by whitlockjc** [comment]
If I use the [petstore example](http://petstore.swagger.io/v2/swagger.json), I do not produce any errors at all during validation:

```
Sway.create({definition: 'http://petstore.swagger.io/v2/swagger.json'}).then(function (api) { console.log(api.validate()); }).catch(function (err) { console.log(err); });
Promise {
  <pending>,
  domain:
   Domain {
     domain: null,
     _events: { error: [Function: debugDomainError] },
     _eventsCount: 1,
     _maxListeners: undefined,
     members: [] } }
> { errors: [], warnings: [] }
```

There are _no_ errors or warnings.  I'm not sure how you're producing an error and I am not.  In fact, the petstore example is in the `sway` repository and is used during its test suite.

I will try to run your sample code now.

**Comment by whitlockjc** [comment]
Your code doesn't even attempt to validate so I'm not sure.  I cannot reproduce your reported issue with the petstore example and `sway`.

**Comment by gruberchris** [comment]
I get the exception "unknown primitive "file" in /type when calling "getSample()" on the parameter object "file" parameter in that route.  I'm sure if you can run my code against this swagger.json you'll see the same error I am seeing.

**Comment by whitlockjc** [comment]
Yeah, running your code was painful because I would had needed Babel or something to get it into a format that Node.js works with _(I tried v8.x)_.  I guess my reproduction didn't get to the part of your code where this happened, my bad.

I do think I understand this now and I can see why this bug would happen.  Should be an easy fix.

**Comment by gruberchris** [comment]
Awesome. Thanks for taking the time. I should have thought about needing babel to run my example. I'll keep an eye out for your fix.

**Comment by whitlockjc** [comment]
Ultimately, the response body for `type: file` could be a string.  Of course, the file type dictates the content of the response body but from a generation perspective...isn't a file at it's core just bytes, or a string from a mock perspective?

**Comment by whitlockjc** [comment]
Simple test to add that reproduces it:

```js
it('should handle file (Issue 159)', function () {
      assert.ok(_.isString(swaggerApi.getOperation('/pet/{petId}/uploadImage', 'post').getParameter('file').getSample()));
    });
```
