### ISSUE TITLE
GET request fails content-type check

### ISSUE THREAD

**Issue by sauvainr** [apigee-127/sway#164]
I got the following error when using a GET request which of course don't have content.. 
`{
  code: 'INVALID_CONTENT_TYPE',
  message: 'Invalid Content-Type (application/octet-stream).  These are supported: application/json'
}`

Work-around was to add 'application/octet-stream' in the consumes of the API.
Is it a known issue?

**Comment by whitlockjc** [comment]
What's interesting is that a `GET` request _can_ have a body and so if a `Content-Type` is present, it will be validated.  We could potentially turn off validating the `Content-Type` if there is no body whenever no request parameter is `in: body`.

**Comment by SteveMorin** [comment]
> We could potentially turn off validating the Content-Type if there is no body whenever no request parameter is in: body.

@whitlockjc Is there a way to do this in the current release? I'm seeing the same issue.

**Comment by whitlockjc** [comment]
I'll get started.

**Comment by MartinDelVecchio** [comment]
I am seeing the same thing on a POST that has no parameters in: body; all parameters are in: query.  It has no consumes: specified, either at the file level or at the operation level.

So I am sending no body, and no Content-Type header.  The error I am getting:

     {"message":"Validation errors","errors":[{"code":"INVALID_CONTENT_TYPE","message":"Invalid Content-Type (application/octet-stream).  These are supported: ","path":[]}]}

I modified my request to send a "Content-Type: text/plain" header,but with no body, and got the above error, but with "text/plain" in place of "application/octet-stream".

And finally, I modified my request to send a "Content-Type: application/json" header, with a body of "{}, and got that same error.

So it seems to me that an API that specifies no parameter in: body, and has no consumes:, and that includes no body and no Content-Type header, should be accepted as valid. 

Does that make sense?

Thanks.

**Comment by whitlockjc** [comment]
Yep, that's what I'll get working on.

**Comment by MartinDelVecchio** [comment]
OK, great.  Thanks!

**Comment by amarzavery** [comment]
The [HTTP RFC spec says](https://tools.ietf.org/html/rfc2616#section-7.2.1) that if the content-type is not provided then "application/octet-stream" should be treated as the default content-type.

>   Any HTTP/1.1 message containing an entity-body SHOULD include a
   Content-Type header field defining the media type of that body. If
   and only if the media type is not given by a Content-Type field, the
   recipient MAY attempt to guess the media type via inspection of its
   content and/or the name extension(s) of the URI used to identify the
   resource. **If the media type remains unknown, the recipient SHOULD
   treat it as type "application/octet-stream".**

**Comment by MartinDelVecchio** [comment]
@amarzavery, not that in my example, my request does not have a body.

**Comment by whitlockjc** [comment]
Well, body of `{}` does not imply empty _"does not have a body"_.  I'd like to see how you're calling the API if you don't mind.  As of right now, I will try to fix things as discussed above.

**Comment by MartinDelVecchio** [comment]
Are you referring to my post?  If so, it seems like you might be responding to this part of it:

> And finally, I modified my request to send a "Content-Type: application/json" header, with a body of "{}, and got that same error.

But please note that the original, actual problem involves a request with no content-type header and no body.  Everything else was an attempt to diagnose the bug in the library that produces this error.

Thanks.

**Comment by whitlockjc** [comment]
I got it.  I've got it sorted, commit coming in a few.  Basically, no `Content-Type` validation for request or response when the body is empty _(`undefined` when called programmatically)_.

**Comment by MartinDelVecchio** [comment]
Thanks!

**Comment by adityaguru149** [comment]
@whitlockjc What release has these changes?

**Comment by adityaguru149** [comment]
I drilled down into the code in node_modules and found the code in the mentioned commit present.
Yet I feel the code does not handle for case ----when body is a empty object (Object {}).
@whitlockjc Can you take a look and confirm?

I'm facing issue for this case.

**Comment by adityaguru149** [comment]
> @adityaguru149 `sway@v2.x+` should have these changes.

@whitlockjc Yes, I could find the code in node_modules.
What about the below case? Could you look into this?

> I drilled down into the code in node_modules and found the code in the mentioned commit present.
> Yet I feel the code does not handle for case ----when body is a empty object (Object {}).
> @whitlockjc Can you take a look and confirm?
> 
> I'm facing issue for this case.

**Comment by whitlockjc** [comment]
An empty body of `{}` is not an empty body but a body with an empty object.  Am I misunderstanding?
