### ISSUE TITLE
Validating nullable types

### ISSUE THREAD

**Issue by amarzavery** [apigee-127/sway#170]
## Problem:
There are services that reuse the same model in request body and response body. At times the model has a sensitive property like `password` or `storageAccountKey` that is required while the model is being used as in the request body and when the service sends the same model back in the response, it sets those sensitive properties with a null value. Now sway will fail with an error null is not a valid "string" type. This is theoretically correct, but it is a noise in the current context.  

Many people in the open api community support `"x-nullable": true` as an extension in their tool chain. 

## A possible solution:

It would be nice if all the model properties that are not marked as `required` or the properties that have `"x-nullable": true`, should be made as a oneOf of that property type or `null` type. That would indicate z-schema to validate the property correctly.

Transforming the model from this:
```json5
"Animal" : {
   "type": "object",
   "required": [ "id", "secretPetName" ]
  "properties": {
      "name": {
        "type" : "string"
      },
       "isWild": {
        "type" : "boolean"
      },
      "id": {
        "type" : "string"
      },
      "secretPetName": {
        "type" : "string",
        "x-nullable": true
      },
    }
}
```

to this:
```json5
"Animal" : {
   "type": "object",
   "required": [ "id" ]
  "properties": {
      "name": {
        "oneOf": [
          { "type" : "string" },
          { "type" : "null" }
        ]
      },
       "isWild": {
        "oneOf": [
          { "type" : "boolean" },
          { "type" : "null" }
        ]
      },
      "id": {
        "type" : "string"
      },
      "secretPetName": {
        "oneOf": [
          { "type" : "string" },
          { "type" : "null" }
        ]
      },
    }
}
```

> Note that we did not change id, since that is a required property. We only modified, optional properties and properties that were marked as `"x-nullable": true`

- Again this should simply be an internal in memory representation of the swagger that is used for validating models. These transformations are not required for semantic validation (since `oneOf` is not supported in `Open API specification 2.0`).

**Comment by whitlockjc** [comment]
This is what custom validators is for.  Since you're referring to using a vendor extension, you would need to register your own validator.  This is possible via [Sway.registerValidator](https://github.com/apigee-127/sway/blob/master/docs/API.md#module_Sway..SwaggerApi+registerValidator) or using `options.customValidators` when using [Sway.create(options)](https://github.com/apigee-127/sway/blob/master/docs/API.md#module_Sway.create).  One thing that isn't available yet is the ability to register custom validators for request/response validation.  I've created an issue that I'll link against.

**Comment by amarzavery** [comment]
Sounds good.

**Comment by amarzavery** [comment]
But this is more than a vendor extension. I want to be supporting nullable types for all the model properties that are not required, apart from the ones that have x-nullable: true present for them?

How would one go about doing that via registerValidator

**Comment by whitlockjc** [comment]
The point I'm trying to make is that OAS doesn't have a concept of nullable so you're asking `sway` to do something that isn't supported natively in OAS.  So you'd have to do this with a vendor extension and a custom validator _(#171)_ to enforce it.

**Comment by amarzavery** [comment]
Ah I see..
