### ISSUE TITLE
MODULE_NOT_FOUND: json-schema-faker/lib 

### ISSUE THREAD

**Issue by thomas-silva-sofi** [apigee-127/sway#188]
Sway accepts new minor versions of json-schema-faker in package.json.
`"json-schema-faker": "^0.5.0-rc15"`

And, sway does not utilize the main script but uses a specific directory reference.
https://github.com/apigee-127/sway/search?q=require+json-schema-faker&unscoped_q=require+json-schema-faker
`mocker = require('json-schema-faker/lib');`

0.5.0-rc15 may have worked, however rc16 moved some files.
https://github.com/json-schema-faker/json-schema-faker/compare/v0.5.0-rc15...next-rc16?diff=split
`  "main": "lib/index.js",
  "main": "dist/json-schema-faker.cjs.js",`

So, as of 3 days ago changes in json-schema-faker broke Sway.
https://github.com/json-schema-faker/json-schema-faker/branches

**Comment by whitlockjc** [comment]
Rolling a new `v2.x` release right now.

**Comment by whitlockjc** [comment]
`sway@2.0.5` fixes this.
