### ISSUE TITLE
Upgrade static-eval dependency in package-lock.json (security concern)

### ISSUE THREAD

**Issue by dinvlad** [apigee-127/sway#203]
Hi @whitlockjc,

Could you please update package dependency chain `json-schema-faker`->`jsonpath`->`static-eval` - the current versions in `package-lock.json` are using `static-eval 2.0.0` that's marked for arbitrary code execution by SourceClear. I believe just re-building the package cache should do the job (`static-eval` should pick up v`2.0.2`).

Thanks!

P.S. Relevant info:
https://github.com/json-schema-faker/json-schema-faker/issues/492
https://www.sourceclear.com/vulnerability-database/vulnerabilities/13351

**Comment by whitlockjc** [comment]
Fixed.
