### ISSUE TITLE
Global (api level) security ignored when resolving operation#securityDefinitions in OAS3

### ISSUE THREAD

**Issue by wickedest** [apigee-127/sway#218]
### Expected outcome
Given an OAS 3.0 spec that defines [`securitySchemes`](https://github.com/OAI/OpenAPI-Specification/blob/master/versions/3.0.2.md#securitySchemeObject) component (e.g. api-key) and a global [`security`](https://github.com/OAI/OpenAPI-Specification/blob/master/versions/3.0.2.md#securityRequirementObject) Requirement Object, the `operation.securityDefinitions` should be `{"api-key":{"in":"query","name":"apikey","type":"apiKey"}}"`.

```yaml
openapi: 3.0.0
servers:
  - description: Sample API
    url: https://sample.io
info:
  description: My sample service
  version: "1.0.0"
  title: Sample API
security:
  - api-key: []
paths:
  /doit:
    get:
      description: Get something
      operationId: getSomething
      responses:
        default:
          description: Success
components:
  securitySchemes:
    api-key:
      in: query
      name: apikey
      type: apiKey
```

### Actual outcome
The `operation.securityDefinitions` is empty `{}`.

The issue may be related to this [code](https://github.com/apigee-127/sway/blob/4719e7201311a6c78d26db4118a4d3f073c06360/lib/types/operation.js#L143-L154) in operation.js - `securityDefinitions` is undefined in OAS3.  Instead, they were renamed to `components.securitySchemes` and the equivalent should be accessible at `pathObject.api.definitionFullyResolved.components.securitySchemes`.

**Comment by whitlockjc** [comment]
OASv3 isn't supported yet, I apologize.  Please use #128 to keep track of that.
