### ISSUE TITLE
Can't handle default and id fields inside JSON Schema

### ISSUE THREAD

**Issue by IvanGoncharov** [apigee-127/sway#29]
It simpler to provide code sample:
```js
var swagger = {
  "definitions": {
    "TestSchema": {
      "properties": {
        "default": {
        },
        "id": {
        },
      },
    },
  },
  "info": {
    "title": "Test sample",
    "version": "v1.0"
  },
  "paths": {},
  "swagger": "2.0"
};

sway.create({definition: swagger})
.then(function (swaggerObj) {
  var result = swaggerObj.validate();
  console.log('works ' + JSON.stringify(swaggerObj.getLastErrors()));
})
.catch(function (error) {
  console.log('error ' + error);
});
```
and it crash: `TypeError: undefined is not a function`
I already fix this issue and will make PR

**Comment by whitlockjc** [comment]
I was worried this could happen, same thing happened to swagger-js when they merged in properties from the schema into the JavaScript object.  I look forward to your PR.

**Comment by IvanGoncharov** [comment]
@whitlockjc I created #30 it not full fix. Because it remove particular scenario of how schema with invalid `id` field could appear. But it doesn't fix z-schema crash.

**Comment by IvanGoncharov** [comment]
@whitlockjc This PR zaggino/z-schema/pull/141 fixed z-schema crash.
And #30 fixes incorrect validation of `properties`.

**Comment by whitlockjc** [comment]
I've merged #30 but there are two questions:

1. You said #30 didn't fix everything, can you elaborate?
2. Do I need to update z-schema?

**Comment by IvanGoncharov** [comment]
In nutshell, sway tried to  check value of `properties` as JSON Schema. One of the checks for check of default so if `default` was present it passed value of `properties` into z-schema as valid schema. 
So sway passed something like this:
```json
{
  "id": {"type": "string"},
  "default": {"type": "integer"}
}
```
Which is valid value for `properties` but invalid JSON Schema.
There is two problems:
  - sway passing `properties` as JSON Schema, fixed in #30 
  - z-schema crashing if `id` field has invalid type, fixed in zaggino/z-schema#141

**Comment by IvanGoncharov** [comment]
> Do I need to update z-schema?

In theory, all `id` objects should be rejected on during syntax validation.
But it always better to update dependencies.

**Comment by whitlockjc** [comment]
Gotcha.  As soon as I update z-schema, I'll close this as I think we've covered everything.  Thanks for your help on this.

**Comment by IvanGoncharov** [comment]
@whitlockjc, I working on another PR and I believe that I will finish today, so you can wait with npm release.

**Comment by whitlockjc** [comment]
Will do.

**Comment by IvanGoncharov** [comment]
@whitlockjc #32 Was change that I wanted to make.
So I will appreciate if you publish NPM package.

**Comment by whitlockjc** [comment]
`sway@v0.3.2` has been released with these changes.

**Comment by IvanGoncharov** [comment]
@whitlockjc Thanks
