### ISSUE TITLE
Schema validation for strings without date format

### ISSUE THREAD

**Issue by mikefre** [apigee-127/sway#41]
Hi,
On line 98 in parameter-value.js, there is a condition about which cases  we do not want to do schema validation. 
The last condition is
//   * The schema is for a string type with date/date-time format and the value is a date

&&
                  (schema.type !== 'string' && !_.isDate(value)))

So when I have a parameter like
      parameters:
        - in: formData
          name: someField
          description: some description
          required: true
          type: string
          format: email

Email format validation is not performed on this field. When I removed that condition,  there is email validation. I would like to ask, whether, in situations where we have string field and format not date, we should do schema validation? Or am I missing something?

**Comment by whitlockjc** [comment]
We should be doing validation for string parameters unless the value is a date.  I think the conditional is wrong.

**Comment by mikefre** [comment]
So something like this?
&&
!(schema.type === 'string' && _.isDate(value) && schema.format === 'date-time')

**Comment by whitlockjc** [comment]
I'm not sure yet.  I'll get to it shortly.
