### ISSUE TITLE
Add semantic validation for missing type parameter

### ISSUE THREAD

**Issue by whitlockjc** [apigee-127/sway#45]
While Swagger allows you to have a schema without a `type` parameter, this is typically a mistake.  We should create a warning for this.

**Comment by IvanGoncharov** [comment]
If you apply couple of rules you can make this warnings very useful.
One such rule is to ignore cases where `allOf` present.
Another one it too show it only if properties tied to one particular type is used:
 - Objects: `properties`, `additionalProperties`, ...
 - Number: `multiplyOf`, `minimum`, ..
 - etc.

So for example if it `{  "properties": {} }` should produce warning.
But for something like `{  "properties": {}, "minimum": "0" }` or `{"description": "..."}` is completely valid.

And this problem doesn't tied to Swagger spec, it common mistake for any JSON Schema.
So I think `z-schema` is good place to implement it.

**Comment by whitlockjc** [comment]
z-schema doing this would be great.  I'll bring it up but I do know there are a number of options outside of Swagger where a type-less schema makes sense.  But for Swagger, it rarely was on purpose and you can have unexpected results.  For example:

```yaml
# ...
  definitions:
    Person:
      properties:
        name:
          type: string
        age:
          type: integer
# ...
```

It's clear you intended `Person` to be an object but the only was a JSON Schema validator will fail validation is if you provide an `Object` but it will blindly pass with non-Object values.

**Comment by IvanGoncharov** [comment]
I think, it matter of lowering number of false positives.
Rules that I wrote is good starting point.
Making it as optional warnings also helps a lot.
I think it's already enough to be useful outside of Swagger.

**Comment by whitlockjc** [comment]
I think that omitting `type` in Swagger is **always** a bad thing but due to how Swagger works, I can see why people might use it.  *(An example of needing to work around Swagger using this is when you have a response that can produce different values.)*  Creating warnings in the Swagger case makes sense because we are telling you that you're doing something not necessarily supported or that it could be a mistake.  I think outside Swagger those things don't apply as much.  Regardless, I'll ask Martin to see what he thinks.

**Comment by whitlockjc** [comment]
The more I think about it, I don't think it's fair for me to enforce this.  While I stand by my opinion above, there are circumstances where you must omit the `type` to work around Swagger.  While I don't agree with the need for this, it's not my place.  Since we have configurable validators, these can easily be added.  Another option where sway could be involved is some configurable error/warning setting(s) to allow you to toggle this when you want it.

I'm closing this but would be glad to open it if people feel strongly about it.
