### ISSUE TITLE
Path parameters are marked as declared but not defined

### ISSUE THREAD

**Issue by runebjerregaard** [apigee-127/sway#47]
I was debugging a validation problem with my swagger specification, and while doing so, I tried to validate the PetStore example in http://editor.swagger.io/.

That gave me a similar error to the one I was trying to solve: 

Path parameter is declared but is not defined: petId

Could there be a problem with validators.js? (I did not investigate yet)

**Comment by whitlockjc** [comment]
When I open both PetStore examples, they render without any errors.  Did you alter the document to produce the error?

**Comment by runebjerregaard** [comment]
Hmm. I'm pretty sure I didn't. But the version I can download now from http://petstore.swagger.io/v2/swagger.json has the parameters all declared and defined. 

Sorry to have bothered you. You can close the issue.

**Comment by whitlockjc** [comment]
Feel free to reopen it if you see the issue again.
