### ISSUE TITLE
sway browser standalone is not making SwaggerApi in window

### ISSUE THREAD

**Issue by saharj** [apigee-127/sway#59]
This file is not making the global object SwaggerApi in window anymore: https://raw.githubusercontent.com/apigee-127/sway/master/browser/sway-standalone-min.js

**Comment by whitlockjc** [comment]
Work on `1.0.0` started a few weeks ago in `master` so any binaries downloaded from there now use `Sway` as the global object, not `SwaggerApi`.  See the release notes: https://github.com/apigee-127/sway/blob/master/RELEASE_NOTES.md#v100-tbd
