### ISSUE TITLE
new getParameter/getValue syntax

### ISSUE THREAD

**Issue by timkuijsten** [apigee-127/sway#65]
While trying to add custom validators for a swagger-express project I ran into this project.

I was wondering if the new api for something like:

    req.swagger.params.query.value

really is:

    req.swagger.operation.getParameter('page').getValue(req).value

This is quite more verbose and I can imagine you guys change this API before making sway public. Especially the seemingly redundant passing of `req` to getValue.

(using swagger-node-runner with the latest sway)

**Comment by whitlockjc** [comment]
The purpose of passing `req` to the API is so we can pull the value from the request object.  So it's not redundant.  I'm not sure how you'd expect `Parameter#getValue` to do anything if it didn't have access to the `req` object.

As for the verbosity, you're comparing two different things.  The first thing you show is a swagger-tools/swagger-node feature that sticks processed parameter values into `req.swagger.params` for convenience.  [sway-connect](https://github.com/whitlockjc/sway-connect) will likely do something else when it's complete.  The second thing you're showing seems to be a swagger-node thing, which I do not control.

Sway is an API and with it being somewhat object oriented, you're bound to have to do some typing to get from one object to another.  The Connect middleware, sway-connect, will likely give you access to the Sway API **and** provide a simplified syntax like you're wanting.  Feel free to chime in on the sway-connect issues as I want to make sure it is better than swagger-tools in all ways.
