### ISSUE TITLE
Optional File in formData

### ISSUE THREAD

**Issue by xun91** [apigee-127/sway#66]
Was trying to allow optional profile_picture when creating user account. Using swagger-node-runner which has sway lib dependency. The attached is the error I've got when omitting the profile_picture field.
Could you please assist? Thank you :)

![screen shot 2016-03-04 at 9 28 07 am](https://cloud.githubusercontent.com/assets/1982412/13515341/75756ea6-e1eb-11e5-9691-65d5ba6fbc7d.png)

Here is the error I've got:

![screen shot 2016-03-04 at 9 21 24 am](https://cloud.githubusercontent.com/assets/1982412/13515248/e47e6b8c-e1ea-11e5-8a23-fdd690445f59.png)

**Comment by xun91** [comment]
Sorry. I think the problem is in swagger node runner.

**Comment by whitlockjc** [comment]
If you find it's here, don't hesitate to reach out.
