### ISSUE TITLE
New release?

### ISSUE THREAD

**Issue by rsinger** [apigee-127/sway#71]
There hasn't been a release since November of last year.  Fixes for two bugs that affect us (https://github.com/apigee-127/sway/issues/60 and https://github.com/apigee-127/sway/issues/39) have been merged, but not released, so we're having to hack solutions around it in the meantime.

I can't imagine we're alone with that, what's the ETA for a new release?

**Comment by whitlockjc** [comment]
I think we were working on a PR from @IvanGoncharov related to #28 but I don't see why we have to.  There are a few simple bug fixes and one PR to take care of.  I'll plan on a `v1.0.0` release today unless someone else suggests otherwise.

**Comment by whitlockjc** [comment]
`sway@v1.0.0` has been released.

**Comment by rsinger** [comment]
:clap:!
