### ISSUE TITLE
expose sway zschema.registerFormat used in helpers.js

### ISSUE THREAD

**Issue by ghost** [apigee-127/sway#74]
I would like to add custom formats to the request and response validators.  To do this right now requires something like:

```
var ZSchema = require('sway/node_modules/z-schema');
ZSchema.registerFormat('my-format', my_format_validator)
```

It would be much nicer to have have access to the modules zschema so it was a matter of:

```
var Sway = require('sway');
var sway.create(...).then(function (api) {
  api.registerFormat('my-format', my_format_validator);
})
```

Since the require('z-schema') exists within helper.js the above interface might not live directly within the SwaggerApi instance but somewhere accessible would be nice.

**Comment by whitlockjc** [comment]
I agree that this would be useful.

**Comment by nazarhussain** [comment]
This would a very useful feature, is there any update on it?

**Comment by whitlockjc** [comment]
We're working on a release as we speak.  We've been trying to get it out over the last couple of weeks but work has been interfering.  The plan is to include this in the next release.

**Comment by nazarhussain** [comment]
@whitlockjc Thanks for this information. What's the expected date of next release?

**Comment by whitlockjc** [comment]
I don't want to give that, only because I'd hate to miss it.  I've given guesses in the past and missed so I'd rather not this time.

**Comment by whitlockjc** [comment]
But I do hope by end of month.

**Comment by nazarhussain** [comment]
@whitlockjc For everyone reference till the feature is released. I figured out a workaround, that is working for me. 
```
require('sway/lib/helpers').getJSONSchemaValidator().constructor.registerFormat('name', fn)
```
