### ISSUE TITLE
How to get "processed" parameter values for in:body 

### ISSUE THREAD

**Issue by entropyfarms** [apigee-127/sway#75]
I have a complex swagger schema for a JSON in:body POST request.  I can get the body value like:

```
var val = op.getParameter('body').getValue(req);
var body = val.value;
```

where op is the specific api.getOperations() element.  How can I get the processed values of the body though?  For instance I have a body like:

```
{
  time: '2016-04-01T00:00:00Z'
}
```

with "time" specified as a type:"string" and format:"date-time" in the api specification.  I see that op.validateRequest recursively validates the document but the .value property does not contain the recursively processed body.

I think it comes down to this line in helper.js (function convertValue):

```
if (_.isUndefined(type)) {
    return value;
  }
```

which stops deeper recursion.  Can you give me a pointer on where to start?

**Comment by whitlockjc** [comment]
What's your schema look like?  If your `type` for the parameter is not available, as in you've got a schema that does not set the `type`, you can end up in this situation.  But I can't be sure without seeing your parameter schema.

**Comment by entropyfarms** [comment]
You are correct, I do not have a "type" listed.  I was more wondering if adding something like:

```
return _.mapValues(schema.properties, function (property_schema, property) {
      return convertValue(property_schema, null, value[property]);
    });
```

would correctly process the structure recursively.  Do you forsee side-effects for other types?  Except for the obvious one if value is null (though solved by swapping the order of the _.isUndefiend checks for type and value).

**Comment by entropyfarms** [comment]
I tried this and it causes all kinds of issues with validation since it uses the processed value and not the raw value.  Though changing to

```
value = this.rawValue
```

in parameter-value::valid does appear to solve that.

**Comment by whitlockjc** [comment]
It should recursively convert values as long as the schema provides the `type`.  We do not make any assumptions for `type` when it is missing because JSON Schema does not require it.

**Comment by entropyfarms** [comment]
noted.  I have type on subproperties and that that is what I want process.  e.g. type:string, format:date-time within the JSON document.

Thank you for the help.

**Comment by whitlockjc** [comment]
Let me know if I can help further or if you find anything not working like you expected/wanted.
