### ISSUE TITLE
api.getPath fails for path parameter in parentheses

### ISSUE THREAD

**Issue by phil-mitchell** [apigee-127/sway#79]
With a path definition like "/Users({id})" api.getPath() fails to find a match.

This notations is defined by the OData spec, so it's not unreasonable to have.

Changing the path definition to "/Users\\({id}\\)" works, but then the generated documentation looks bad, and the double-escape sequence causes the YAML to look extra ugly as well.

I think it is necessary to escape certain characters (such as parentheses) before calling into pathToRegexp().

**Comment by whitlockjc** [comment]
I'll give it a peek.  I assume this is when using `api.getPath(req)` where `req` is a request object?

**Comment by philbert82** [comment]
That's right.  I'm using this indirectly through swagger-node-runner.  It calls api.getPath(req) and fails to find a match.

**Comment by whitlockjc** [comment]
Interesting.  I do know swagger-node-runner is using an old version of sway iirc and that *might* be the case.  Let me do some digging.

**Comment by theganyo** [comment]
Just FYI, swagger-node-runner is still on Sway 0.6.0 because of breaking changes when Sway went to 1.0... and there's been no time to look into why yet.

**Comment by whitlockjc** [comment]
I'll update the two of you when I find something.  I'll spend some time on Sway this evening.

**Comment by whitlockjc** [comment]
I am able to reproduce this with the current release.  It seems like an issue with taking an OpenAPI/Swagger path and converting it to a regular expression.  Basically parentheses are special and while blindly escaping might work, I've opened an issue with the library we use for this to get their opinion.
