### ISSUE TITLE
Maximum call stack size exceeded error

### ISSUE THREAD

**Issue by saharj** [apigee-127/sway#82]
Copying from https://github.com/swagger-api/swagger-editor/issues/917

I've made it into a GIST: https://gist.github.com/paul42/4a85567c9136eba058ecc5e571b2b4ef
So I think the issue is I have too many references - I've trimmed out a lot of the stuff and i still get the stack error, but if I remove a refernce, then it goes back to working - 

to reproduce: 
open editor.swagger.io
file->paste json
paste in json from gist
ensure you get max stack exceeded error
remove a single property from a definition that has $ref: '#/definitions/ ' etc
notice that the swagger editor resumes working

is the editor only able to handle a certain amount of references, or am I making mine wrong?

Thanks again for taking a look, I appreciate it.

**Comment by whitlockjc** [comment]
I'm marking this as a duplicate of #85 since it's got a sample YAML file that reproduces the issue and does so with an impact on performance.
