### ISSUE TITLE
how to avoid caching validation result

### ISSUE THREAD

**Issue by mailingmuthu** [apigee-127/sway#91]
It is storing the validation report in cache what is the option or param i should pass to avoid caching the validation result 

sway.create({ definition: filePath })
   .then(function (result) {
         console.log(result.validate().errors)
   }

**Comment by whitlockjc** [comment]
There is no validation cache but if you alter the originating document and re-validate, you need to use `sway.create` again.

**Comment by mailingmuthu** [comment]
HI whitlockjc, 
Could you please provide sample code for that ?
