### ISSUE TITLE
$ref in a path results in an Unknown Error

### ISSUE THREAD

**Issue by zeiphon** [apigee-127/sway#92]
Looking at the swagger specification it seems that a `$ref` should be allowed in place of a path element, but this doesn't seem to be accepted by Sway.
For example, see the following YAML:

```

---
swagger: '2.0'
info:
  version: 1.0.0
  title: Test Api
  description: Test
schemes:
  - http
host: test.com
basePath: /api
paths:
  /my-actual-path/:
    $ref: '#/paths/x-mypath'

  x-mypath:
    get:
      description: Test
      responses:
        200:
          description: Response test
          schema:
            type: object
            properties:
              id:
                type: integer
```

This currently results in an Unknown Error.

**Comment by whitlockjc** [comment]
I'll take a look.

**Comment by CWThomson** [comment]
I came across the same issue - references to other YAML files used to work when I was using swagger-express-mw - version 0.6 but with 0.7 (which I believe upgraded the version of sway) this broke.

Below are a couple of changes that I made to get it to work - I'll submit a pull request but there may be a better way to do this. Note below changes require a change to the swagger-node-runner module as well

In lib/types/operation.js

Line 65
`this.consumes = definition.consumes || pathObject.api.consumes || [];`
to
`this.consumes = definitionFullyResolved.consumes || pathObject.api.consumes || [];`

Line 72
`this.produces = definition.produces || pathObject.api.produces || [];`
to
`this.produces = definitionFullyResolved.produces || pathObject.api.produces || [];`


In swagger-node-runner/fittings/swagger_router.js
Line 62
`var operationId = operation.definition['operationId'] || context.request.method.toLowerCase();`
to
`var definition = operation.definition || operation.definitionFullyResolved;
      var operationId = definition['operationId'] || context.request.method.toLowerCase();`

**Comment by CWThomson** [comment]
Just to clarify the error i was getting was

`Error in callback! Tossing to global error handler. TypeError: Cannot read property 'consumes' of undefined
    at new Operation (node_modules/sway/lib/types/operation.js:65:29)
    at node_modules/sway/lib/types/path.js:104:23
    at node_modules/lodash/lodash.js:929:11
    at node_modules/lodash/lodash.js:4738:15
    at baseForOwn (node_modules/lodash/lodash.js:2879:24)
    at node_modules/lodash/lodash.js:4707:18
    at baseReduce (node_modules/lodash/lodash.js:926:5)
    at Function.reduce (node_modules/lodash/lodash.js:9354:14)
    at new Path (node_modules/sway/lib/types/path.js:100:29)
    at node_modules/sway/lib/types/api.js:91:12
node_modules/swagger-node-runner/index.js:249`

**Comment by whitlockjc** [comment]
This was documented in the release notes: https://github.com/apigee-127/sway/blob/master/RELEASE_NOTES.md#v100-2016-04-04  So it seems the other library needs to be updated?

**Comment by whitlockjc** [comment]
I see what you mean.  So in the event you had your `consumes`/`produces` in a referenced location, it wasn't resolving.  Got it.

**Comment by CWThomson** [comment]
Exactly:

Example:
```yaml
swagger: "2.0"
info:
  version: "0.0.1"
  title: API
host: localhost:10010
basePath: /v1
schemes:
  - https
paths:
  /examplepath:
    $ref: "api/swagger/subresource.yaml#/Resource"
```

subresource.yaml
```yaml
Resource:
  x-swagger-router-controller: controllername
    post:
      description: Send
      operationId: send
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - in: body
          name: param1
          description: blah
          required: true
          schema:
            $ref: api/swagger/datatypes.yaml#/Request
      responses:
        "201" :
          description: Success
        default:
          description: Error
          schema:
            $ref: api/swagger/datatypes.yaml#/ErrorResponse
```

**Comment by Celadora** [comment]
This commit isn't making it to the npm package, when we reinstall swagger-node-runner it is missing.

**Comment by lumaxis** [comment]
@Celadora This patch has not been released to npm yet, see #121

**Comment by ArjunHariharan** [comment]
When do you plan to release this version?

**Comment by Lotti** [comment]
I still encounter this bug :\ any news?
I'm using
    "swagger-express-mw": "^0.7.0",
    "swagger-node-runner": "^0.7.3",

**Comment by whitlockjc** [comment]
The `sway` release fixing this isn't out yet:

https://github.com/apigee-127/sway/blob/master/RELEASE_NOTES.md#tbd

We're close to a new release.
