### ISSUE TITLE
Allow for more strict request/response validation

### ISSUE THREAD

**Issue by whitlockjc** [apigee-127/sway#94]
In swagger-tools, we've talked about having a _strict mode_ where request/response parameters that were not explicitly defined would create an error/warning.  What I would like to see is some configurable feature where you can turn on and alter _strict mode_ for your needs such that you are alerted whenever a request/response is made that deviates from your Swagger document.  This was requested in #93.

**Comment by mbrand** [comment]
Would really love to see this 👍

**Comment by jmichel84** [comment]
+1 Would really need this, having to double check everything before saving to the db is a pain.

**Comment by whitlockjc** [comment]
It will be in the next release which we are currently working on.

**Comment by Fonz001** [comment]
When is the next release coming up? :-)

**Comment by whitlockjc** [comment]
Soon I hope.  I've been trying to spend more time on this but I have been struggling.

**Comment by iblazevic** [comment]
@whitlockjc any updates on the new release. If there is any help I can provide let me know, we really need this feature

**Comment by whitlockjc** [comment]
I'm working on it as we speak.  _(Check the commits from today.)_

**Comment by whitlockjc** [comment]
Can someone give me an idea of exactly what you want here?  I can think of a plethora of ways that _"strict mode"_ could be done but I can also think of cases where they might not always be wanted _(request headers for example)_.

**Comment by jmichel84** [comment]
I agree with @iblazevic.

My biggest issue is that parameters not defined in the swagger schema (path, body or formData), do not throw errors. This forces me to validate the payload in the server side source code before persisting it to the database. Having a strict validation would permit to reduce the amount of source validation by delegating the task to the middleware.

The behavior I would expect from a strict validation is that any parameter not defined in the swagger operation and sent via the HTTP request triggers an error.
An optional improvement would be to be able to choose in the configuration if these undefined parameters trigger an error or only a warning.

Thank you for considering this improvement!

**Comment by whitlockjc** [comment]
What if we had it so that request validation took a `strictMode` option that can be one of two things:

1. `boolean`: If `true`, all inputs/outputs are strict
2. `object`: A key/value pair of where the keys are `in` values _(`header`, `formData`, `query`)_ whose value is a boolean and dictates if that particular input/output is validated strictly or not _(Default value if the key isn't present is `false`.)_

`body` isn't necessary because you can already do that with the schema definition _(`additionalProperties: false`)_ and so is `path`, since all path parameters are treated as `required` and shouldn't allow for providing extra path parameters or the route matcher wouldn't match.  So `body` and `path` will not be handled specially in this case.  Thoughts?

**Example (all on)**

```js
var results = op.validateRequest(req, true);
```

**Example (all on but headers)**
```js
var results = op.validateRequest(req, {
  formData: true,
  query: true,
});
```

**Comment by iblazevic** [comment]
I didn't know I can achieve this behavior for the body validation with `additionalProperties`, I didn't come across that option in the docs. I'll have to test that for the body as that might just cover my strict body validation.

Is `additionalProperties` documented anywhere?

As for you proposal for `_header_`, `_formData_` and `_query_` I think it makes perfect sense.

**Comment by whitlockjc** [comment]
`additionalProperties` is a JSON Schema feature and Swagger 2.0 uses it.  It's mentioned [here](https://github.com/OAI/OpenAPI-Specification/blob/master/versions/2.0.md#schema-object) from a Swagger perspective and it's documented [here](https://spacetelescope.github.io/understanding-json-schema/reference/object.html#properties) from a JSON Schema perspective.  `additionalProperties` is definitely the way to do this for `body` where `body` is a complex type, an `array` of `object`s or an `object`.

**Comment by iblazevic** [comment]
I missed that, that works great for the body. Adding the above-discussed validation for query and headers will round the validation completely IMO.

**Comment by whitlockjc** [comment]
There is an order of operation here that needs to be discussed.  Should strict mode validation only happen _after_ the existing validation happens _(so strict mode validation only happens for valid requests/responses)_ or should it happen _before_ the existing validation?

**Comment by whitlockjc** [comment]
Or maybe it's not an either/or, but an always?

**Comment by iblazevic** [comment]
I would prefer always if possible. It's mostly subjective but I like getting all errors at once, it's a cleaner experience IMO.

**Comment by whitlockjc** [comment]
First pass of strict mode validation is in.  `Operation#validateRequest`, `Operation#validateResponse` and `Response#validateResponse` now have an optional second argument _(`strictMode`)_ that dictates whether strict mode validation is on/off and to what portion(s) of the request/response needs to be validated _(`formData` is request only, `headers` are request and response and `query` is request only.  Please review the API documentation for more details.)_

Please let me know if this is what you were hoping for.
