### ISSUE TITLE
dependencies

### ISSUE THREAD

**Issue by osher** [apigee-127/sway#97]
Did you look in the resulting node_modules folder?

Have a look here:
http://npm.anvaka.com/#/view/2d/sway

Why do we need both `superagent` and `request`? Did you notice how bloated the 2nd is?
I mean, I see that `json-refs` uses `path-loader` that uses `superagent`, where `sway` preferes `request`.

I advise you to consider if you really need `request`.
If you could replace it with `superagent` - you'll end up with a much more elegant package. 
If you really depend on features of `request` - then... tough luck :stuck_out_tongue:

**Comment by whitlockjc** [comment]
sway does not use request unless it's a transitive dependency.  sway uses path-loader and json-refs alone, both of which use superagent.

**Comment by osher** [comment]
it appears that z-schema uses it

**Comment by osher** [comment]
![image](https://cloud.githubusercontent.com/assets/803101/18677362/35ee35e2-7f61-11e6-8a16-302e9eb90217.png)

**Comment by whitlockjc** [comment]
I am all for reconsidering some of the dependencies being used by `sway` but of course, I cannot dictate/own the transitive dependencies I inherit from others.

**Comment by TheToolbox** [comment]
The above PR removed `request` as a dependency for `z-schema`. A quick update to `z-schema@3.18.0` should cut off that whole portion of the tree. I ran tests locally and it passes. I'll send a PR shortly, or feel free to do it yourselves!

**Comment by osher** [comment]
chapeau!

**Comment by whitlockjc** [comment]
Gotcha.  I'll update `z-schema` in the next release.
